### ISSUE TITLE
fps of mobilenet ssd with tensorRt 

### ISSUE THREAD

**Issue by EhabMedhat** [NVIDIA-Jetson/tf_trt_models#3]
what  is exact fps u get when run mobilenet SSD   on jetsontx2

**Comment by jaybdub-nv** [comment]
In the [execution time table](https://github.com/NVIDIA-Jetson/tf_trt_models#models-1) we measured 50.5 milliseconds per frame.  This comes to (1000 / 50.5) = 19.8 FPS.  This can vary based off of system configuration and parameters in the object detection configuration file.
